[project]
name = "inference-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inference>=0.51.0",
    "pillow>=10.0.0",
    "ultralytics>=8.3.179",
]
