[project]
name = "inference-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pillow>=10.0.0",
    "ultralytics>=8.3.179",
    "numpy",
    "opencv-python",
    "inference>=0.35.0,<0.51",
    "supervision",
    "fastapi>=0.110.3",
    "uvicorn",
    "lerobot>=0.3.0",
    "feetech-servo-sdk>=1.0.0",
    "ncnn>=1.0.20250916",
    "onnx>=1.19.0",
]
